variables: secrets.yml
schedules:
  - tasks: ['populate-*', 'clean-*']
    schedule:
      hour: 0
  - tasks: ['fill-*', '*-rss']
    schedule:
      hour: '2-8/2'
  - tasks: ['*-discover', '*-manual']
    schedule:
      hour: 2
  - tasks: ['move-*', download-subtitles]
    schedule:
      minute: 15,45
  - tasks: ['sync-*']
    interval:
      weeks: 1


templates:

##### Series config#
  series:
    thetvdb_lookup: yes
    tvmaze_lookup: yes
    trakt_lookup: yes
    configure_series:
      from:
        entry_list: trakt-series
      settings:
        identified_by: ep
        timeframe: 1 hours
        target: webrip+ <720p !10bit !h265
        quality: webrip+ 720p-1080p !10bit !h265
        propers: 48 hours
        specials: no
        season_packs: 3
    content_size:
      min: 100
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'


##### Movies config#
  movies-1080p:
    tmdb_lookup: yes
    movie_list: trakt-movies
    quality: 1080p webdl+ !10bit !h265
    content_size:
      min: 2000
      max: 20000

  movies-720p:
    tmdb_lookup: yes
    movie_list: trakt-movies
    quality: 720p webdl+ !10bit !h265
    content_size:
      min: 900
      max: 7000

##### Transmission config#
  transmission-anchors:
    _transmission-settings: &transmission-settings
      host: "{? transmission.host ?}"
      port: 9091
      username: "{? transmission.user ?}"
      password: "{? transmission.pass ?}"

##### Common rejections#
  reject:
    regexp:
      reject:
        - \b(s|d)ub(s|bed|lado|titulado)?\b
        - \bhc\b
        - \bdual\b
        - \b3d\b
        - \bfre(nch)?\b
        - \bita(lian)?\b
        - \bspa(nish)?\b
        - \bger(man)?\b
        - \bcastellano\b
        - \brus(sian)?\b
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'


##### ADVANCED SETTINGS #####

##### Global config#
  global:
    no_entries_ok: yes
    pathscrub: windows
    free_space:
      path: "/{? folder.root ?}"
      space: 5000
    # Requires log_filter plugin
    log_filter:
      task:
        - marked seen
        - because quality already downloaded
        - because episode has already been downloaded
        - Task does not have any
      move:
        - left because it exceeds safety value
        - does not exists (anymore)
      urlrewriter:
        - URL rewritten to
      enzyme.mkv:
        - Reading
        - Processing
      enzyme.parsers.ebml.core:
        - ignored
        - Maximum level
      subliminal.video:
        - Scanning video
      parser_internal:
        - appears to be an episode pack
      content_size:
        - rejecting
      search_rss:
        - Error
      assume_quality:
        - ""
      utils.requests:
        - Waiting

##### Common torrents config#
  torrents:
    torrent_alive:
      min_seeds: 3
      reject_for: 15 minutes
    magnets: no
    convert_magnet:
      timeout: 20 seconds
      force: yes
    # Might need to disable if you are getting errors connecting to https sources
    # Can remove if you upgrade to python 2.7.9+ or install requests[security]
    #verify_ssl_certificates: no
    domain_delay:
      thepiratebay.se: 10 seconds
      thepiratebay.org: 10 seconds
      limetorrents: 3 seconds
      anidex.info: 3 seconds
      bt-chat.com: 1 seconds
      ezrss.it: 1 seconds
      showrss.info: 2 seconds
      torlock.eu: 1 seconds
      torrenticity.com: 1 seconds
      zooqle.com: 2 seconds

##### Transmission series config#
  transmission-series:
    transmission:
      <<: *transmission-settings
      main_file_only: yes
      include_subs: yes
      rename_like_files: yes
      content_filename: "{{tvdb_series_name|default(series_name)|pathscrub}} - {{tvdb_ep_id|default(series_id)}}{% if tvdb_ep_name|default(False) %} - {{tvdb_ep_name|pathscrub}}{% endif %}{% if quality|default(False) %} - [{{quality}}]{% endif %}"
      path: "/{? folder.root ?}{? folder.downmedia ?}{{tvdb_series_name|default(series_name)|pathscrub}}/"

##### Transmission movies config#
  transmission-movies:
    transmission:
      <<: *transmission-settings
      main_file_only: yes
      include_subs: yes
      rename_like_files: yes
      content_filename: "{{tmdb_name|pathscrub}} ({{tmdb_year}}){% if quality|default(False) %} - [{{quality}}]{% endif %}"
      path: "/{? folder.root ?}{? folder.downmedia ?}{{movie_name|pathscrub}}"

##### Pushbullet config#
#  pushbullet:
#    notify:
#      entries:
#        title: "[flexget] {{task}}"
#        message: "{{title}}"
#        via:
#          - pushbullet:
#              api_key: "{? pushbullet.api ?}"

##### Disable builtins for some tasks#
  disable-seen-retry:
    disable:
      - seen
      - seen_info_hash
      - retry_failed

##### Series metainfo mainly for move and update tasks#
  series-metainfo:
    metainfo_series: yes
    thetvdb_lookup: yes

##### Guessit parsing for some series tasks, not applied to all tasks because it causes issues with "name (year)" based series, like scandal#
  series-guessit:
    parsing:
      series: guessit

##### Movies metainfo mainly for move and update tasks#
  movies-metainfo:
    tmdb_lookup: yes
    parsing:
      movie: guessit


tasks:

########## SERIES ##########

##### Populates the series database with the files on the library, to avoid duplicate downloads#
  populate-series-db:
    priority: 1
    template:
      - series-metainfo
    seen: local
    filesystem:
      path: "/{? folder.root ?}{? folder.series ?}"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    configure_series:
      from:
        filesystem:
          path: "/{? folder.root ?}{? folder.series ?}"
          retrieve: dirs
      settings:
        tracking: no
        identified_by: ep



##### Fetch, format and output trakt series list to a custom entry list#
  fill-series-list:
    priority: 2
    template:
      - disable-seen-retry
      - series-metainfo
    list_clear:
      what:
        - entry_list: trakt-series
    trakt_list:
      account: "{? trakt.account ?}"
      list: "{? trakt.series ?}"
      type: shows
      strip_dates: yes
    accept_all: yes
    set:
      title: "{{tvdb_series_name|escape|replace('&#39;', '')}}"
      set_series_begin: yes
    list_add:
      - entry_list: trakt-series


##### (First time run) Sync Flexget database with watched status in Trakt#  
  setbegin-series-trakt:
    priority: 4
    next_trakt_episodes:
      account: "{? trakt.account ?}"
      list: "{? trakt.series ?}"
      context: watched
      position: next
      strip_dates: yes
    accept_all: yes 
    set_series_begin: yes

  

##### Download episodes from manually downloaded torrents#
  download-series-manual:
    priority: 5
    template:
      - disable-seen-retry
      - series-metainfo
      - series-guessit
      - transmission-series
    filesystem:
      path: "/{? folder.root ?}{? folder.downmedia ?}"
      mask: '*.torrent'
    accept_all: yes
    exec:
      on_output:
        for_accepted: rm -f "{{location}}"


##### Download episodes from RSS feeds#
  download-series-rss:
    priority: 6
    template:
      - series
      - reject
      - torrents
      - transmission-series
    inputs:
      - rss: http://showrss.info/other/all.rss      
      - rss: https://eztv.ag/ezrss.xml
      - rss: https://rarbg.to/rssdd.php?category=1;18;41;49
      - rss: 
          url: https://zooqle.com/search?q=%2A+category%3ATV&fmt=rss
          title: 'torrent:fileName'
      - rss: https://www.limetorrents.cc/rss/20/
      - rss: https://www.t411.al/rss/?cat=433


##### Discover and download older episodes#
  download-series-discover:
    priority: 7
    template:
      - series
      - reject
      - torrents
      - transmission-series
    magnets: yes
    convert_magnet:
      timeout: 10 seconds
      force: yes
    discover:
      release_estimations: strict
      interval: 15 minutes
      what:
        - next_series_seasons: yes
        - next_series_episodes: yes
      from:
        - piratebay:
            category: highres tv
        - limetorrents:
            category: tv
        - rarbg:
            category: [1, 18, 41, 49]


########## MOVIES ##########

##### Remove manually downloaded movies from the movie queue and trakt list#
  clean-movies-queue:
    priority: 11
    template:
      - disable-seen-retry
      - movies-metainfo
    filesystem:
      path: "/{? folder.root ?}{? folder.movies ?}"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    list_remove:
      - movie_list: trakt-movies
      - trakt_list:
          account: "{? trakt.account ?}"
          list: "{? trakt.movies ?}"
          type: movies


##### Fill the movie queue with movies from trakt list#
  fill-movies-queue:
    priority: 12
    trakt_list:
      account: "{? trakt.account ?}"
      list: "{? trakt.movies ?}"
      type: movies
      strip_dates: yes
    accept_all: yes
    list_add:
      - movie_list: trakt-movies


##### Download movies manually downloaded torrents#
  download-movies-manual:
    priority: 13
    template:
      - disable-seen-retry
      - movies-metainfo
      - transmission-movies
    filesystem:
      path: "/{? folder.root ?}{? folder.downmedia ?}"
      mask: '*.torrent'
    accept_all: yes
    exec:
      on_output:
        for_accepted: rm -f "{{location}}"
    list_remove:
      - movie_list: trakt-movies
      - trakt_list:
          account: "{? trakt.account ?}"
          list: "{? trakt.movies ?}"
          type: movies


##### Discover and download 1080p movies#
  download-movies-1080p-discover:
    priority: 14
    template:
      - movies-1080p
      - reject
      - torrents
      - transmission-movies
    exists_movie:
      - "/{? folder.root ?}{? folder.downmedia ?}"
      - "/{? folder.root ?}{? folder.movies ?}"
    magnets: yes
    convert_magnet:
      timeout: 10 seconds
      force: yes
    discover:
      release_estimations: loose
      interval: 15 minutes
      what:
        - movie_list: trakt-movies
      from:
        - piratebay:
            category: highres movies
        - limetorrents:
            category: movies
    list_match:
      from:
        - movie_list: trakt-movies
    list_remove:
      - trakt_list:
          account: "{? trakt.account ?}"
          list: "{? trakt.movies ?}"
          type: movies


##### Discover and download 720p movies, if the movie is not recent#
  download-movies-720p-discover:
    priority: 15
    template:
      - movies-720p
      - reject
      - torrents
      - transmission-movies
    exists_movie:
      - "/{? folder.root ?}{? folder.downmedia ?}"
      - "/{? folder.root ?}{? folder.movies ?}"
    magnets: yes
    convert_magnet:
      timeout: 10 seconds
      force: yes
    discover:
      release_estimations: loose
      interval: 15 minutes
      what:
        - movie_list: trakt-movies
      from:
        - piratebay:
            category: highres movies
        - limetorrents:
            category: movies
    if:
      - tmdb_year > now.year - 1: reject
    list_match:
      from:
        - movie_list: trakt-movies
    list_remove:
      - trakt_list:
          account: "{? trakt.account ?}"
          list: "{? trakt.movies ?}"
          type: movies


########## LIBRARY ##########

##### Move series from downloads folder to respective folders, along with existing subtitles and adding the files to the subtitle queue#
  move-series:
    priority: 21
    template:
      - disable-seen-retry
      - series-metainfo
    filesystem:
      path: "/{? folder.root ?}{? folder.downmedia ?}"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    move:
      to: "/{? folder.root ?}{? folder.series ?}{{tvdb_series_name|escape|replace('&#39;', '')|pathscrub}}/"
      rename: "{{tvdb_series_name|escape|replace('&#39;', '')|pathscrub}} - {{tvdb_ep_id|default(series_id)}}{% if tvdb_ep_name|default(False) %} - {{tvdb_ep_name|pathscrub}}{% endif %}{% if quality|default(False) %} - [{{quality}}]{% endif %}{% if release_group|default(False) %} - [{{release_group}}]{% endif %}"
      along:
        extensions:
          - srt
          - sub
        subdirs:
          - Subs
      clean_source: 50
    kodi_library:
      action: scan
      category: video
      url: http://localhost
      port: 8080
    list_add:
      - subtitle_list:
          list: subtitles
          path: "{{location}}"
          remove_after: 7 days
    exec:
      on_exit:
        phase: find "/{? folder.root ?}{? folder.downmedia ?}"* -type d -empty -delete



##### Move movies from downloads folder to the movies folder, along with possible subtitles and adding the files to the subtitle queue#

  move-movies:
    priority: 22
    template:
      - disable-seen-retry
      - movies-metainfo
    filesystem:
      path: "/{? folder.root ?}{? folder.downmedia ?}"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    regexp:
      reject:
        - \btrailer\b
        - \bsample\b
    move:
      to: "/{? folder.root ?}{? folder.movies ?}"
      rename: "{{tmdb_name|pathscrub}} ({{tmdb_year}}){% if quality|default(False) %} - [{{quality}}]{% endif %}{% if release_group|default(False) %} - [{{release_group}}]{% endif %}"
      along:
        extensions:
          - srt
          - sub
        subdirs:
          - Subs
      clean_source: 100
    kodi_library:
      action: scan
      category: video
      url: http://localhost
      port: 8080
    list_add:
      - subtitle_list:
          list: subtitles
          path: "{{location}}"
          remove_after: 7 days
    exec:
      on_exit:
        phase: find "/{? folder.root ?}{? folder.downmedia ?}"* -type d -empty -delete



##### Download subtitles for the previously queued files#
  download-subtitles:
    priority: 23
    template:
      - disable-seen-retry
    subtitle_list:
      list: subtitles
    list_match:
      from:
        - subtitle_list:
            list: subtitles
    subliminal:
      exact_match: yes
      languages:
        - eng


##### Clean finished torrents from transmission#
  clean-transmission:
    priority: 24
    disable: details
    clean_transmission:
      <<: *transmission-settings
      finished_for: 1 day


########## UPDATES ##########
